### ISSUE TITLE
Selecting a large size photo for the event poster to be uploaded crashes the app

### ISSUE THREAD

**Issue by maximum-maxness** [CMPUT301W24T05/PlaceHolderProjectName#150]
This is an edge case, but I thought it might be important to look into how we're loading and displaying image files. I tried to upload a large image (25MB!) to be the event poster, but after I selected the image in the picker, the app crashed with the following error in the logcat:

```logs 
2024-03-25 13:15:15.239 19357-19357 PhotoPicker             ca.cmput301t05.placeholder           D  Selected URI: content://media/picker/0/com.android.providers.media.photopicker/media/1000000019
2024-03-25 13:15:16.060 19357-19357 AndroidRuntime          ca.cmput301t05.placeholder           D  Shutting down VM
2024-03-25 13:15:16.063 19357-19357 AndroidRuntime          ca.cmput301t05.placeholder           E  FATAL EXCEPTION: main
                                                                                                    Process: ca.cmput301t05.placeholder, PID: 19357
                                                                                                    java.lang.RuntimeException: Canvas: trying to draw too large(179044352bytes) bitmap.
                                                                                                    	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:266)
                                                                                                    	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:94)
                                                                                                    	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:549)
                                                                                                    	at android.widget.ImageView.onDraw(ImageView.java:1446)
                                                                                                    	at android.view.View.draw(View.java:23889)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22756)
                                                                                                    	at android.view.View.draw(View.java:23620)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4556)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4317)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22747)
                                                                                                    	at android.view.View.draw(View.java:23620)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4556)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4317)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22747)
                                                                                                    	at android.view.View.draw(View.java:23620)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4556)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4317)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22747)
                                                                                                    	at android.view.View.draw(View.java:23620)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4556)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4317)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22747)
                                                                                                    	at android.view.View.draw(View.java:23620)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4556)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4317)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22747)
                                                                                                    	at android.view.View.draw(View.java:23620)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4556)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4317)
                                                                                                    	at android.view.View.draw(View.java:23892)
                                                                                                    	at com.android.internal.policy.DecorView.draw(DecorView.java:809)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22756)
                                                                                                    	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:694)
                                                                                                    	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:700)
                                                                                                    	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)
                                                                                                    	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4939)
                                                                                                    	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4643)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3822)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2465)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9305)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1339)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:882)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
2024-03-25 13:15:16.075 19357-19357 Process                 ca.cmput301t05.placeholder           I  Sending signal. PID: 19357 SIG: 9
```

It looks like this has something to do with how we're loading images from the picker into the imageview element. Needs more investigation.

**Comment by maximum-maxness** [comment]
I fixed this by implementing the same image picker for event posters as profile images
